### ISSUE TITLE
File caching

### ISSUE THREAD

**Issue by nitrosx** [SciCatProject/scitacean#48]
I was think if we could implement a rudimentary file caching following this simple workflow:
- user indicate that a local copy of the file is needed by using the provide_locally function
```
dataset.files[x].provide_locally(
    local_folder,
    downloader=file_transfer_function,
    checksum_algorithm=algorithm
)
```
- scitacean find the local path where the file should be saved
- scitacean check if a file by that name is already present
- if no file is present, it downloads the file
- if the file is present and we have the original checksum and the checksum algorithm:
  - Scitacean computes the has of the local file
  - if it matches the hash of the remote one, the local file is used
  - if it does not match, it downloads the remote file overwriting the local one

**Comment by jl-wynen** [comment]
As far as I can tell, this would be a basic solution.

But keep in mind that computing the hash can be expensive, too. (No where near as expensive as a download but still.) Maybe we can come up with a better mechanism that takes file modification times into account. If a file hasn't been modified since we last computed its checksum, then the checksum hasn't changed. But this requires storing the checksum somewhere.

**Comment by jl-wynen** [comment]
Let's go with your suggestion for now. We can always optimise further if it turns out that users wait a lot for checksums to compute.

**Comment by nitrosx** [comment]
Fine be me.
