### ISSUE TITLE
File download

### ISSUE THREAD

**Issue by nitrosx** [SciCatProject/scitacean#52]
As a user, I would prefer to have a File method to download the individual file, while using the client download method when I have to download many or all of them.

To download the single file, I would expect to be able to write something similar to this code:
`new_dataset = dataset.files[0].download()`

while I would use the client download method to download all of them, with the following syntax:
`new_dataset = client.download_files(dataset, target="download", select=True)

**Comment by nitrosx** [comment]
What about a solution like this one:

1. when I retrieve a dataset using: 
`dataset = client.get_dataset("20.500.12269/72fe3ff6-105b-4c7f-b9d0-073b67c90ec3")`
The dataset and the files objects returned contain also a reference to the client used to download.
2. when you download the files, you can download through the client with:
`dataset_with_local_file = client.download_files(dataset, target="download", select="flux.dat")`
3. or you can download them individually with:
```
file = dataset.files[0]
dataset_with_local_file = file.download()
```
using the client used to retrieve them originally
4. or another option is:
```
file = dataset.files[0]
dataset_with_local_file = file.download(new_client)
``` 
if we want to download the file using a different client

Solution in 3 and 4 should make a call to _client.download_files_ with the specified client.

**Comment by jl-wynen** [comment]
I am not a fan of keeping a ref to the client as explained above. But I would be fine with 4. However, `file.download(client)` would return a new *file* not a *dataset*. So the old dataset would still think that the file has not been downloaded. This is because two-way references will cause trouble. So the file cannot produce a new dataset since it doesn't know what dataset it belongs to.

**Comment by jl-wynen** [comment]
I don't want objects to diverge as in option 4 (dataset and downloaded file have different information). And since we shouldn't have two-way references or store references to clients in datasets or files, I don't see an immediate way to improve the interface.
So I'm closing the issue for now. Feel free to reopen if you still think that the interface needs improving.
